[package]
name = "latex-ide-ui"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["macro", "html"] }
dioxus-signals = { workspace = true }
dioxus-hooks = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Storage", "Document", "Element", "DomTokenList", "HtmlElement"] }

[features]
default = []
desktop = ["dioxus/desktop"]
web = ["dioxus/web"]